SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `categories` ADD `ttl` INT(11) UNSIGNED NOT NULL DEFAULT 604800 AFTER `name`;

ALTER TABLE `categories` ADD INDEX `ttl` (`ttl`) ;

SET FOREIGN_KEY_CHECKS = 1;
